name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/terraform
  pull_request:
    branches:
      - feature/terraform

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.GITHUB_ACTOR }} # GitHub username
        password: ${{ secrets.DOCKER_ACCESS }} # PAT stored as a secret

    - name: Build and push API image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.GITHUB_ACTOR }}/api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.GITHUB_ACTOR }} # GitHub username
        password: ${{ secrets.DOCKER_ACCESS }} # PAT stored as a secret

    - name: Pull and run Docker Compose
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d
